insert into VENUE_LEVEL (levelID,levelName, price, rowCount, seatsPerRow,remainingSeats) values (1, 'Orchestra', 100.00, 25, 50, 1250);
insert into VENUE_LEVEL (levelID,levelName, price, rowCount, seatsPerRow,remainingSeats) values (2, 'Main', 75.00, 20, 100, 2000);
insert into VENUE_LEVEL (levelID,levelName, price, rowCount, seatsPerRow,remainingSeats) values (3, 'Balcony 1', 50.00, 15, 100, 1500);
insert into VENUE_LEVEL (levelID,levelName, price, rowCount, seatsPerRow,remainingSeats) values (4, 'Balcony 2', 40.00, 15, 100, 1500);